
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lorelei
 */
public class inventory2 extends javax.swing.JFrame {

    /**
     * Creates new form inventory2
     */
    public inventory2() {
        initComponents();
        Connect ();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
public final void Connect(){
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(inventory2.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(inventory2.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("Error connecting to database: " + ex.getMessage());
    }
}
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        addbtn1 = new javax.swing.JButton();
        brand_txt = new javax.swing.JTextField();
        descp_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        itemnum_txt = new javax.swing.JTextField();
        dept_txt = new javax.swing.JTextField();
        rem_txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 397, 75, -1));

        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 75, -1));

        delete_btn.setText("DELETE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 75, -1));

        addbtn1.setText("ADD");
        addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 75, -1));
        jPanel1.add(brand_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, -1));
        jPanel1.add(descp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 220, 50));

        jLabel5.setText("DEPARTMENT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel4.setText("ITEM NAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));

        jLabel1.setText("CPE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel2.setText("NO. OF ITEMS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("DESCRIPTION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setText("COMMENTS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        itemnum_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnum_txtActionPerformed(evt);
            }
        });
        jPanel1.add(itemnum_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 220, -1));

        dept_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept_txtActionPerformed(evt);
            }
        });
        jPanel1.add(dept_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 220, -1));
        jPanel1.add(rem_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, 50));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 397, 75, -1));

        jTabbedPane1.addTab("CPE", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 370, 340));

        jTabbedPane1.addTab("OVERVIEW", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtn1ActionPerformed
                // TODO add your handling code here:
        
        String item =itemnum_txt.getText();
        String description =descp_txt.getText();
        String brand =brand_txt.getText();
        String department =dept_txt.getText();
        String remarks =rem_txt.getText();
        
        try {
            pst =  con.prepareStatement ("INSERT INTO `cpe`(`ID`, `Description`, `Brand`, `Department`, `Remarks`) VALUES (?,?,?,?,?)");
            pst.setString(1, item);
            pst.setString(2, description);
            pst.setString(3, brand);
            pst.setString(4, department);
            pst.setString(5, remarks);
            
            int rowsInserted= pst.executeUpdate();
            
            
            if (rowsInserted>0){
                JOptionPane.showMessageDialog(this," ACCEPTED NA PAREH");
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(inventory2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addbtn1ActionPerformed

    private void itemnum_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnum_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnum_txtActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        String item = itemnum_txt.getText();
        try {
            String sql = "DELETE FROM ce WHERE Id = ? ";
            pst =con.prepareStatement(sql);
            pst.setString(1, item);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this," DELETED NA PAREH");

        } catch (Exception e) {
            System.out.println(e);
        }
        itemnum_txt.setText("");
        descp_txt.setText("");
        brand_txt.setText("");
        dept_txt.setText("");
        rem_txt.setText("");
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        String item = itemnum_txt.getText();
        String description = descp_txt.getText();
        String brnd = brand_txt.getText();
        String department = dept_txt.getText();
        String remarks = rem_txt.getText();
        try {

            String sql = "UPDATE ce SET  Description = ?, Brand = ?,Department= ?,Remarks= ? WHERE Id=?";

            pst = con.prepareStatement(sql);
            pst.setString(1, description);
            pst.setString(2, brnd);
            pst.setString(3, department);
            pst.setString(4, remarks);
            pst.setString(5, item);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this," UPDATED NA PAREH");

        } catch (Exception e) {
            System.out.println(e);

        }
        itemnum_txt.setText("");
        descp_txt.setText("");
        brand_txt.setText("");
        dept_txt.setText("");
        rem_txt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_update_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inventory w1= new inventory ();
        w1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void dept_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dept_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventory2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventory2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventory2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventory2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventory2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn1;
    private javax.swing.JTextField brand_txt;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField dept_txt;
    private javax.swing.JTextField descp_txt;
    private javax.swing.JTextField itemnum_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rem_txt;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
